all:
  children:
    local:
      hosts:
        localhost:
    servers:
      children:
        baremetal:
          children:
            pihole:
              hosts:
                pi.hole:
              vars:
                ADD_ROLES:
                  - pihole
                  - pihole_stats_lcd
            loadbalancer:
              hosts:
                load-balancer-1.tgp:
              vars:
                ADD_ROLES:
                  - nginx
                  - nginx_stats_lcd
            nfs:
              hosts:
                k8s-nfs-1.tgp:
              vars:
                ADD_ROLES:
                  - nfs
            k8s:
              hosts:
                k8s-node-1.tgp:
                k8s-node-2.tgp:
                k8s-node-3.tgp:
              vars:
                ADD_ROLES: [k3s_node]
                # K3S_MASTER is more just the first node since we're installing in a HA configuration
                K3S_MASTER: k8s-node-1.tgp
        oracle:
          children:
            opihole:
              hosts:
                140.238.134.55
              vars:
                ADD_ROLES: [pihole]
            odocker:
              hosts:
                140.238.137.39:
              vars:
                ADD_ROLES: [docker]

          vars:
            ansible_user: ubuntu
            DNS_SERVER: 140.238.134.55

  # Defaults
  vars:
    ADD_ROLES: []
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: dennis
    BAT_VERSION: 0.18.3
    BLINK_VERSION: 2.1.0
    CHANGE_DNS_SERVER: false
    CTOP_VERSION: 0.7.3
    DNS_SERVER: 192.168.1.11
    DOCKER_COMPOSE_VERSION: 1.26.0
    EXA_VERSION: 0.10.1
    HELM_DIFF_VERSION: 3.1.3
    HELM_SECRETS_VERSION: 3.8.3
    HELM_VERSION: 3.6.3
    INFLUXDB2_BUCKET: homelab
    INFLUXDB2_ORG: homelab
    INFLUXDB2_URL: http://influxdb2.tgp
    K3S_CLUSTER_INIT: true
    K3S_MASTER_EXTRA_OPTS: ''
    K3S_VERSION: v1.21.1+k3s1
    K9S_VERSION: 0.24.15
    MY_DOMAIN: pleasenoddos.com
    MY_EMAIL: dennis.zhang.nrg@gmail.com
    SOPS_VERSION: 3.6.1
    TFENV_VERSION: 2.2.2
    UNATTENDED_UPGRADES_STATE: absent
