---

all:
  children:
    local:
      hosts:
        localhost:
    servers:
      children:
        pihole:
          hosts:
            surface-pihole.tgp:
          vars:
            ADD_ROLES: []
        loadbalancer:
          hosts:
            load-balancer-1.tgp:
          vars:
            ADD_ROLES:
              - nginx
              - nginx_stats_lcd
            BITWARDEN_IP: 192.168.1.57
            DENNIS_SITE_IP: 192.168.1.52
            KUBE_OPS_VIEW_IP: 192.168.1.51
            MY_DOMAIN: pleasenoddos.com
            MATTERMOST_IP: 192.168.1.56
            NEXTCLOUD_IP: 192.168.1.61
            WHOOGLE_IP: 192.168.1.60
            WIREGUARD_TRAFFIC_IP: 192.168.1.59
            XYZZY_IP: 192.168.1.63
        kubernetes:
          hosts:
            k8s-node-1.tgp:
          vars:
            ADD_ROLES:
              - k8s_node
              - nfs

  vars:
    MY_EMAIL: dennis.zhang.nrg@gmail.com
    ansible_python_interpreter: /usr/bin/python3
    BAT_VERSION: 0.17.0
    CTOP_VERSION: 0.7.3
    DOCKER_COMPOSE_VERSION: 1.26.0
    UNATTENDED_UPGRADES_STATE: absent
    HELM_VERSION: 3.4.1
    HELMSMAN_VERSION: 3.4.6
    INFLUXDB_DBNAME: homelab
    INFLUXDB_URL: http://influxdb.tgp:8086
    K8S_MASTER: k8s-node-1.tgp
    K9S_VERSION: 0.24.0
    METALLB_IP_RANGE: 192.168.1.50-192.168.1.99
    MICROK8S_ADDONS:
      - dns
      - fluentd
      - metrics-server
      - metallb
      - storage
    MICROK8S_CHANNEL: 1.19/stable
    PIHOLE_SERVER_IP: 192.168.1.11
    USER: dennis
