---

all:
  children:
    local:
      hosts:
        localhost:
    servers:
      children:
        pihole:
          hosts:
            pi.hole:
          vars:
            ADD_ROLES:
              - pihole_blink
        loadbalancer:
          hosts:
            load-balancer-1.tgp:
          vars:
            ADD_ROLES:
              - nginx
              - nginx_stats_lcd
            BITWARDEN_IP: 192.168.1.253
            DENNIS_SITE_IP: 192.168.1.100
            FRESHRSS_IP: 192.168.1.247
            KUBE_OPS_VIEW_IP: 192.168.1.51
            MY_DOMAIN: pleasenoddos.com
            MATTERMOST_IP: 192.168.1.251
            NAVIDROME_IP: 192.168.1.248
            OWNCAST_IP: 192.168.1.246
            SEARX_IP: 192.168.1.252
            WIREGUARD_TRAFFIC_IP: 192.168.1.250
        kubernetes:
          children:
            x86:
              hosts:
                k8s-node-1.tgp:
                  install_canonical_livepatch: True
              vars:
                ADD_ROLES:
                  - k8s_node
                  - k3s_node
                  - nfs
            arm64:
              hosts:
                k8s-node-2.tgp:
                k8s-node-3.tgp:
              vars:
                ADD_ROLES:
                  - k3s_node

  # Defaults
  vars:
    ADD_ROLES: []
    ansible_python_interpreter: /usr/bin/python3
    BAT_VERSION: 0.17.1
    BLINK_VERSION: 2.1.0
    CTOP_VERSION: 0.7.3
    DOCKER_COMPOSE_VERSION: 1.26.0
    HELM_VERSION: 3.4.2
    HELMSMAN_VERSION: 3.4.6
    INFLUXDB_DBNAME: homelab
    INFLUXDB_URL: http://influxdb.tgp:8086
    K3S_VERSION: v1.20.0+k3s2
    K3S_MASTER: k8s-node-2.tgp
    K8S_MASTER: k8s-node-1.tgp
    K9S_VERSION: 0.24.2
    METALLB_IP_RANGE: 192.168.1.50-192.168.1.254
    MICROK8S_ADDONS:
      - dns
      - metrics-server
      - metallb
      - storage
    MICROK8S_CHANNEL: 1.20/stable
    MICROK8S_SNAP_REFRESH_TIME: fri,16:00
    MY_EMAIL: dennis.zhang.nrg@gmail.com
    PIHOLE_SERVER_IP: 192.168.1.11
    UNATTENDED_UPGRADES_STATE: absent
    USER: dennis
