---

all:
  children:
    localhost:
      hosts:
        127.0.0.1
    loadbalancer:
      hosts:
        mysurface3.tgp
      vars:
        ADD_ROLES:
          - haproxy
          - dns_crypt
    kubernetes:
      hosts:
        myserver.tgp
      vars:
        ADD_ROLES:
          - k8s_node
  vars:
    BAT_VERSION: 0.15.4
    CTOP_VERSION: 0.7.3
    DENNIS_SITE_IP: 192.168.1.52
    DOCKER_COMPOSE_VERSION: 1.26.0
    INFLUXDB_URL: http://influxdb.tgp:8086
    INFLUXDB_DBNAME: homelab
    K8S_MASTER: myserver.tgp
    K9S_VERSION: 0.21.2
    OPENVPN_IP: 192.168.1.53
    METALLB_IP_RANGE: 192.168.1.50-192.168.1.99
    MICROK8S_CHANNEL: 1.18/stable
    MY_DOMAIN: pleasenoddos.com
    USER: dennis
    MICROK8S_ADDONS:
      - dns
      - metrics-server
      - metallb
    PIHOLE_SERVER_IP: 192.168.1.11
