all:
  children:
    local:
      hosts:
        localhost:
    servers:
      children:
        sandbox:
          hosts:
            surface.tgp
        pihole:
          hosts:
            pi.hole:
          vars:
            ADD_ROLES:
              - pihole
              - pihole_stats_lcd
        loadbalancer:
          hosts:
            load-balancer-1.tgp:
          vars:
            ADD_ROLES:
              - nginx
              - nginx_stats_lcd
        kubernetes:
          children:
            x86:
              hosts:
                k8s-node-1.tgp:
                  install_canonical_livepatch: True
                  ADD_ROLES:
                    - nfs
                    - k3s_node
            arm64:
              hosts:
                k8s-node-2.tgp:
              vars:
                ADD_ROLES:
                  - k3s_node
                  - node_stats_lcd

  # Defaults
  vars:
    ADD_ROLES: []
    ansible_python_interpreter: /usr/bin/python3
    BAT_VERSION: 0.18.1
    BLINK_VERSION: 2.1.0
    CTOP_VERSION: 0.7.3
    DOCKER_COMPOSE_VERSION: 1.26.0
    HELM_VERSION: 3.5.4
    HELM_SECRETS_VERSION: 3.6.1
    HELM_DIFF_VERSION: 3.1.3
    INFLUXDB_DBNAME: homelab
    INFLUXDB_URL: http://influxdb.tgp
    K3S_MASTER: k8s-node-1.tgp
    K3S_VERSION: v1.20.0+k3s2
    K9S_VERSION: 0.24.8
    MY_DOMAIN: pleasenoddos.com
    MY_EMAIL: dennis.zhang.nrg@gmail.com
    PIHOLE_SERVER_IP: 192.168.1.11
    SOPS_VERSION: 3.6.1
    UNATTENDED_UPGRADES_STATE: absent
    USER: dennis
