---

all:
  children:
    local:
      hosts:
        localhost:
    servers:
      children:
        pihole:
          hosts:
            pi.hole:
          vars:
            ADD_ROLES:
              - pihole_blink
        loadbalancer:
          hosts:
            load-balancer-1.tgp:
          vars:
            ADD_ROLES:
              - nginx
              - nginx_stats_lcd
            WIREGUARD_TRAFFIC_IP: 192.168.1.250
        kubernetes:
          children:
            x86:
              hosts:
                k8s-node-1.tgp:
                  install_canonical_livepatch: True
              vars:
                ADD_ROLES:
                  - k3s_node
                  - nfs
            arm64:
              hosts:
                k8s-node-2.tgp:
                k8s-node-3.tgp:
              vars:
                ADD_ROLES:
                  - k3s_node

  # Defaults
  vars:
    ADD_ROLES: []
    ansible_python_interpreter: /usr/bin/python3
    BAT_VERSION: 0.17.1
    BLINK_VERSION: 2.1.0
    CTOP_VERSION: 0.7.3
    DOCKER_COMPOSE_VERSION: 1.26.0
    HELM_VERSION: 3.5.0
    HELMSMAN_VERSION: 3.6.3
    INFLUXDB_DBNAME: homelab
    INFLUXDB_URL: http://influxdb.tgp
    K3S_INGRESS: k3s-ingress.tgp
    K3S_MASTER: k8s-node-1.tgp
    K3S_VERSION: v1.20.0+k3s2
    K9S_VERSION: 0.24.2
    MY_DOMAIN: pleasenoddos.com
    MY_EMAIL: dennis.zhang.nrg@gmail.com
    PIHOLE_SERVER_IP: 192.168.1.11
    UNATTENDED_UPGRADES_STATE: absent
    USER: dennis
