all:
  children:
    local:
      hosts:
        localhost:
      vars:
        ENABLE_CANONICAL_LIVEPATCH: true
        ADD_ROLES:
          - docker
    servers:
      children:
        baremetal:
          children:
            k8s:
              hosts:
                k8s-high-1.tgp:
                  K3S_EXTRA_OPTS: --node-label performance=high
                k8s-med-1.tgp:
                  K3S_EXTRA_OPTS: --node-label performance=medium
                k8s-med-2.tgp:
                  K3S_EXTRA_OPTS: --node-label performance=medium
              vars:
                # K3S_INIT_NODE is more just the first node since we're installing in a HA configuration
                ADD_ROLES: [k3s_node_control]
                K3S_EXTRA_OPTS: '--tls-san k8s-ingress.tgp'
                K3S_INIT_NODE: k8s-high-1.tgp
        oracle:
          children:
            ok8s:
              hosts:
                150.230.31.244:
              vars:
                ADD_ROLES: [k3s_node_control]
                K3S_EXTRA_OPTS: '--tls-san 150.230.31.244'
                K3S_INIT_NODE: 150.230.31.244
          vars:
            ansible_user: ubuntu

  # Defaults
  vars:
    ansible_ssh_private_key_file: ~/.ssh/homelab
    ADD_ROLES: []
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: dennis
    BAT_VERSION: 0.24.0
    BLINK_VERSION: 2.1.0
    ENABLE_CANONICAL_LIVEPATCH: false
    EXA_VERSION: 0.10.1
    HELM_DIFF_VERSION: 3.8.1
    HELM_SECRETS_VERSION: 4.5.1
    HELM_VERSION: 3.13.3
    INFLUXDB2_BUCKET: homelab
    INFLUXDB2_ORG: homelab
    INFLUXDB2_URL: https://influx.pleasenoddos.com
    K3S_COMMON_SERVER_OPTS: --disable traefik --tls-san k8s-ingress.tgp
    K3S_EXTRA_OPTS: ''
    K3S_VERSION: v1.28.3+k3s2
    K9S_VERSION: 0.31.5
    MY_DOMAIN: pleasenoddos.com
    MY_EMAIL: dennis.zhang.nrg@gmail.com
    SOPS_VERSION: 3.8.1
    TFENV_VERSION: 2.2.2
    UNATTENDED_UPGRADES_STATE: absent
