---

all:
  children:
    myserver:
      hosts:
        myserver.tgp
      vars:
        IS_K8S_MASTER: True
    mysurface3:
      hosts:
        mysurface3.tgp
      vars:
        INSTALL_DOCKER: True
  vars:
    USER: dennis
    CTOP_VERSION: 0.7.3
    DOCKER_COMPOSE_VERSION: 1.26.0
    MICROK8S_CHANNEL: 1.18/stable
    MICROK8S_ADDONS:
      - dns
      - metrics-server
    PIHOLE_SERVER_IP: 192.168.1.11
