all:
  children:
    local:
      hosts:
        localhost:
      vars:
        ADD_ROLES:
          - docker
    servers:
      children:
        baremetal:
          children:
            # pihole:
            #   hosts:
            #     pi-hole:
            #   vars:
            #     ADD_ROLES:
            #       - pihole
            #       - pihole_stats_lcd
            #     PIHOLE_LISTEN_ADDRESS: 10.69.69.2
            #     PIHOLE_INTERFACE: eth0
            k8s:
              hosts:
                k8s-high-1.tgp:
                  K3S_EXTRA_OPTS: --node-label performance=high
                  ADD_ROLES: [k3s_node_control]
                k8s-med-1.tgp:
                  K3S_EXTRA_OPTS: --node-label performance=medium
                  ADD_ROLES: [k3s_node_control]
                k8s-med-2.tgp:
                  K3S_EXTRA_OPTS: --node-label performance=medium --node-label gpu=true
                  ADD_ROLES: [k3s_node_control]
                k8s-low-1.tgp:
                  K3S_EXTRA_OPTS: --node-label performance=low
                  ADD_ROLES: [k3s_node_control]
                k8s-arm-1.tgp:
                  K3S_EXTRA_OPTS: --node-label performance=low
                  ADD_ROLES:
                    - k3s_node_worker
                    - node_stats_lcd
              vars:
                # K3S_INIT_NODE is more just the first node since we're installing in a HA configuration
                K3S_INIT_NODE: k8s-high-1.tgp
        oracle:
          children:
            # opihole:
            #   hosts:
            #     140.238.134.55:
            #   vars:
            #     ADD_ROLES: [pihole]
            #     PIHOLE_LISTEN_ADDRESS: 140.238.134.55
            #     PIHOLE_INTERFACE: ens3
            ok8s:
              hosts:
                150.230.31.244:
              vars:
                ADD_ROLES: [k3s_node_control]
                K3S_EXTRA_OPTS: '--tls-san 150.230.31.244'
                K3S_INIT_NODE: 150.230.31.244
          vars:
            ansible_user: ubuntu

  # Defaults
  vars:
    ansible_ssh_private_key_file: ~/.ssh/homelab
    ADD_ROLES: []
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: dennis
    BAT_VERSION: 0.21.0
    BLINK_VERSION: 2.1.0
    EXA_VERSION: 0.10.1
    HELM_DIFF_VERSION: 3.2.0
    HELM_SECRETS_VERSION: 3.13.0
    HELM_VERSION: 3.9.3
    INFLUXDB2_BUCKET: homelab
    INFLUXDB2_ORG: homelab
    INFLUXDB2_URL: https://influx.pleasenoddos.com
    K3S_COMMON_SERVER_OPTS: --disable traefik
    K3S_EXTRA_OPTS: ''
    K3S_VERSION: v1.23.4+k3s1
    K9S_VERSION: 0.26.3
    MY_DOMAIN: pleasenoddos.com
    MY_EMAIL: dennis.zhang.nrg@gmail.com
    SOPS_VERSION: 3.6.1
    TFENV_VERSION: 2.2.2
    UNATTENDED_UPGRADES_STATE: absent
