---

all:
  children:
    localhost:
      hosts:
        127.0.0.1
    servers:
      children:
        loadbalancer:
          hosts:
            mysurface3.tgp
          vars:
            ADD_ROLES:
              - nginx
              - dns_crypt
            BITWARDEN_IP: 192.168.1.57
            DENNIS_SITE_IP: 192.168.1.52
            KUBE_OPS_VIEW_IP: 192.168.1.51
            MY_DOMAIN: pleasenoddos.com
            MATTERMOST_IP: 192.168.1.56
            WHOOGLE_IP: 192.168.1.60
            WIREGUARD_TRAFFIC_IP: 192.168.1.59
        kubernetes:
          hosts:
            myserver.tgp
          vars:
            ADD_ROLES:
              - k8s_node
  vars:
    BAT_VERSION: 0.15.4
    CTOP_VERSION: 0.7.3
    DOCKER_COMPOSE_VERSION: 1.26.0
    HELM_VERSION: 3.2.4
    HELMSMAN_VERSION: 3.4.4
    INFLUXDB_DBNAME: homelab
    INFLUXDB_URL: http://influxdb.tgp:8086
    K8S_MASTER: myserver.tgp
    K9S_VERSION: 0.21.5
    METALLB_IP_RANGE: 192.168.1.50-192.168.1.99
    MICROK8S_ADDONS:
      - dns
      - metrics-server
      - metallb
    MICROK8S_CHANNEL: 1.18/stable

    OPENVPN_IP: 192.168.1.53
    PIHOLE_SERVER_IP: 192.168.1.11
    USER: dennis
