---

all:
  children:
    kubernetes:
      hosts:
        myserver.tgp
    loadbalancer:
      hosts:
        mysurface3.tgp
  vars:
    USER: dennis
    CTOP_VERSION: 0.7.3
    DOCKER_COMPOSE_VERSION: 1.26.0
    K8S_MASTER: myserver.tgp
    MICROK8S_CHANNEL: 1.18/stable
    MICROK8S_ADDONS:
      - dns
      - metrics-server
      - metallb
    METALLB_IP_RANGE: 192.168.1.50-192.168.1.99
    PIHOLE_SERVER_IP: 192.168.1.11
