all:
  children:
    local:
      hosts:
        localhost:
    servers:
      children:
        baremetal:
          children:
            pihole:
              hosts:
                pi.hole:
              vars:
                ADD_ROLES:
                  - pihole
                  - pihole_stats_lcd
                PIHOLE_LISTEN_ADDRESS: 192.168.1.11
                PIHOLE_INTERFACE: eth0
            loadbalancer:
              hosts:
                load-balancer-1.tgp:
              vars:
                ADD_ROLES:
                  - nginx
                  - nginx_stats_lcd
            k8s:
              hosts:
                k8s-node-1.tgp:
                  K3S_EXTRA_OPTS: --node-label performance=medium type=app
                k8s-node-2.tgp:
                  K3S_EXTRA_OPTS: --node-label performance=medium type=app
                k8s-node-3.tgp:
                  K3S_EXTRA_OPTS: --node-label performance=low type=app
                k8s-node-4.tgp:
                  K3S_EXTRA_OPTS: --node-label performance=medium --node-label type=database
              vars:
                ADD_ROLES: [k3s_node]
                # K3S_INIT_NODE is more just the first node since we're installing in a HA configuration
                K3S_INIT_NODE: k8s-node-1.tgp
        oracle:
          children:
            opihole:
              hosts:
                140.238.134.55:
              vars:
                ADD_ROLES: [pihole]
                PIHOLE_LISTEN_ADDRESS: 140.238.134.55
                PIHOLE_INTERFACE: ens3
            ok8s:
              hosts:
                140.238.137.39:
              vars:
                ADD_ROLES: [k3s_node]
                K3S_EXTRA_OPTS: '--tls-san 140.238.137.39'
                K3S_INIT_NODE: 140.238.137.39
          vars:
            ansible_user: ubuntu

  # Defaults
  vars:
    ADD_ROLES: []
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: dennis
    BAT_VERSION: 0.18.3
    BLINK_VERSION: 2.1.0
    DOCKER_COMPOSE_CLI_VERSION: v2.0.0-rc.1
    DOCKER_COMPOSE_VERSION: 1.26.0
    EXA_VERSION: 0.10.1
    HELM_DIFF_VERSION: 3.1.3
    HELM_SECRETS_VERSION: 3.11.0
    HELM_VERSION: 3.7.1
    INFLUXDB2_BUCKET: homelab
    INFLUXDB2_ORG: homelab
    INFLUXDB2_URL: https://influx.pleasenoddos.com
    K3S_CLUSTER_INIT: true
    K3S_EXTRA_OPTS: ''
    K3S_VERSION: v1.21.1+k3s1
    K9S_VERSION: 0.25.9
    MY_DOMAIN: pleasenoddos.com
    MY_EMAIL: dennis.zhang.nrg@gmail.com
    SOPS_VERSION: 3.6.1
    TFENV_VERSION: 2.2.2
    UNATTENDED_UPGRADES_STATE: absent
