- name: Restart host
  reboot:
    reboot_timeout: 60
  become: yes

- import_tasks: unattended-upgrades.yml
  become: yes

- import_tasks: telegraf.yml
  become: yes

- name: Restart sshd service
  service:
    name: sshd
    state: restarted
  become: yes

- name: Restart resolvconf service
  service:
    name: resolvconf
    state: restarted
  become: yes

- name: Restart systemd-logind service
  service:
    name: systemd-logind
    state: restarted
  become: yes
