# Use vim for editor
export VISUAL=vim
export EDITOR="$VISUAL"

export PATH="$HOME/.local/bin:$HOME/bin:$PATH"

# This must be set for PGP decryption
export GPG_TTY=$(tty)

alias ls='exa'
alias k='kubectl'
alias a='ansible -i group_vars/site.yml'
alias b='bat'
alias f='fly -t homelab'
alias h="HASTE_SERVER=https://haste.pleasenoddos.com haste"
alias g='git'
alias gpr='g pull -r'
alias gcan='g commit --amend --no-edit'
alias t='terraform'
alias tp='t plan'
alias ta='t apply'
alias taa='t apply -auto-approve'

cheat() {
    curl cheat.sh/${1}
}

# Git branch in prompt.
PS1='\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\] $(__git_ps1 "(%s)")\$ '


# HSTR configuration - add this to ~/.bashrc
alias hh=hstr                    # hh to be alias for hstr
export HSTR_CONFIG=hicolor       # get more colors
shopt -s histappend              # append new history items to .bash_history
export HISTCONTROL=ignorespace   # leading space hides commands from history
export HISTFILESIZE=10000        # increase history file size (default is 500)
export HISTSIZE=${HISTFILESIZE}  # increase history size (default is 500)
# ensure synchronization between bash memory and history file
export PROMPT_COMMAND="history -a; history -n; ${PROMPT_COMMAND}"
# if this is interactive shell, then bind hstr to Ctrl-r (for Vi mode check doc)
if [[ $- =~ .*i.* ]]; then bind '"\C-r": "\C-a hstr -- \C-j"'; fi
# if this is interactive shell, then bind 'kill last command' to Ctrl-x k
if [[ $- =~ .*i.* ]]; then bind '"\C-xk": "\C-a hstr -k \C-j"'; fi

# Oracle SDK
[[ -e "/home/dennis/lib/oracle-cli/lib/python3.6/site-packages/oci_cli/bin/oci_autocomplete.sh" ]] && source "/home/dennis/lib/oracle-cli/lib/python3.6/site-packages/oci_cli/bin/oci_autocomplete.sh"
