---

- name: Install my bash_profile
  copy:
    src: bash_profile
    dest: /home/dennis/.bash_profile

- name: Install tools
  apt:
    pkg:
      - curl
      - make
      - screen
    update_cache: yes
  become: yes

- import_tasks: kubectl.yml
  become: yes
