
- name: Install my bash_profile
  ansible.builtin.copy:
    src: bash_profile
    dest: /home/{{ USER }}/.bash_profile

- import_tasks: sops.yml
  become: yes

- import_tasks: kubectl.yml
  become: yes

- import_tasks: k9s.yml
  become: yes

- import_tasks: helm3.yml
