- name: Download git-prompt.sh script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh
    dest: /home/{{ ansible_user }}/.git-prompt.sh
    mode: 0644

- name: Install local tools
  ansible.builtin.apt:
    pkg:
      - jq
  become: true

- name: Install my bash_aliases
  ansible.builtin.copy:
    src: bash_aliases
    dest: /home/{{ ansible_user }}/.bash_aliases

- import_tasks: sops.yml
  become: true

- import_tasks: kubectl.yml
  become: true

- import_tasks: k9s.yml
  become: true

- import_tasks: helm3.yml

- import_tasks: tfenv.yml

- import_tasks: helmsman.yml
  become: true

- import_tasks: docker.yml
  become: true
  when: '"docker" in ADD_ROLES'
