---

- name: Install my bash_profile
  copy:
    src: bash_profile
    dest: /home/dennis/.bash_profile

- name: Install local tools
  apt:
    pkg: make
    update_cache: yes
  become: yes

- import_tasks: kubectl.yml
  become: yes

- import_tasks: k9s.yml
  become: yes

- import_tasks: helm3.yml

- import_tasks: hstr.yml
