- name: Download git-prompt.sh script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh
    dest: /home/{{ ansible_user }}/.git-prompt.sh
    mode: 0644

- name: Install local tools
  ansible.builtin.apt:
    pkg:
      - jq
  become: yes

- name: Install my bash_profile
  ansible.builtin.copy:
    src: bash_profile
    dest: /home/{{ ansible_user }}/.bash_profile

- import_tasks: sops.yml
  become: yes

- import_tasks: kubectl.yml
  become: yes

- import_tasks: k9s.yml
  become: yes

- import_tasks: helm3.yml

- import_tasks: tfenv.yml
