- name: Check if sops version is installed
  command: sops --version
  register: sops_version_command
  ignore_errors: yes
  changed_when: False

- name: set sops version fact
  set_fact:
    sops_version: "{{ sops_version_command.stdout | regex_search(regexp) }}"
  vars:
    regexp: '[0-9]+\.[0-9]+\.[0-9]+'
    cacheable: yes
  when: sops_version_command.rc == 0

- name: Download sops x86_64
  get_url:
    url: https://github.com/mozilla/sops/releases/download/v{{ SOPS_VERSION }}/sops-v{{ SOPS_VERSION }}.linux
    dest: /usr/local/bin/sops
    mode: '0755'
  when:
    - sops_version_command.rc != 0 or SOPS_VERSION != sops_version
