- name: Check if Spruce version is installed
  command: spruce --version
  register: spruce_version_command
  ignore_errors: yes
  changed_when: False

- name: set Spruce version fact
  set_fact:
    spruce_version: "{{ spruce_version_command.stdout | regex_search(regexp) }}"
  vars:
    regexp: '[0-9]+\.[0-9]+\.[0-9]+'
    cacheable: yes
  when: spruce_version_command.rc == 0

- name: Install Spruce
  get_url:
    url: https://github.com/geofffranks/spruce/releases/download/v{{ SPURCE_VERSION }}/spruce-linux-amd64
    dest: /usr/local/bin/spruce
    mode: 0755
  when: spruce_version_command.rc != 0 or SPURCE_VERSION != spruce_version
