- name: Check if yj version is installed
  ansible.builtin.shell: yj -v
  register: yj_version_command
  ignore_errors: yes
  changed_when: False

- name: set yj version fact
  set_fact:
    yj_version: "{{ yj_version_command.stdout | regex_search(regexp) }}"
  vars:
    regexp: '[0-9]+\.[0-9]+\.[0-9]+'
    cacheable: yes
  when: yj_version_command.rc == 0

- name: Install yj
  ansible.builtin.get_url:
    url: "https://github.com/sclevine/yj/releases/download/v{{ YJ_VERSION }}/yj-linux"
    dest: /usr/local/bin/yj
    mode: '0755'
  when: yj_version_command.rc != 0 or YJ_VERSION != yj_version
