- name: Create InfluxDB 2 directory
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
  with_items:
    - /opt/dc-services
    - /opt/dc-services/ssl
    - /opt/dc-services/nginx
    - /data/influxdb2

- name: Place Lets Encrypt Private Key
  ansible.builtin.copy:
    content: "{{ LETSENCRYPT_PRIV_KEY }}"
    dest: /opt/dc-services/ssl/privkey.pem
    mode: 600
  notify: Restart dc-nginx service
  become: yes

- name: Place Lets Encrypt Certs
  ansible.builtin.copy:
    content: "{{ LETSENCRYPT_CERT }}"
    dest: /opt/dc-services/ssl/fullchain.pem
    mode: 600
  notify: Restart dc-nginx service
  become: yes

- name: Place Nginx conf
  ansible.builtin.template:
    src: dc-services/nginx.conf.j2
    dest: /opt/dc-services/nginx/nginx.conf
    mode: 600
  notify: Restart dc-nginx service
  become: yes

- name: Install docker-compose file
  ansible.builtin.template:
    src: dc-services/docker-compose.yaml.j2
    dest: /opt/dc-services/docker-compose.yaml

- name: Start docker compose
  ansible.builtin.command:
    chdir: /opt/dc-services
    cmd: docker compose up -d
