---

- name: Check if DNS Crypt is Installed
  command: /opt/dnscrypt-proxy/dnscrypt-proxy --version
  register: dnscrypt_version_command
  ignore_errors: yes
  changed_when: False

- name: set DNS Crypt version fact
  set_fact:
    dns_crypt_version: "{{ dnscrypt_version_command.stdout | regex_search(regexp) }}"
  vars:
    regexp: '[0-9]+\.[0-9]+\.[0-9]+'
    cacheable: yes

- name: Install DNS Crypt Proxy
  unarchive:
    src: https://github.com/DNSCrypt/dnscrypt-proxy/releases/download/{{ DNS_CRYPT_VERSION }}/dnscrypt-proxy-linux_x86_64-{{ DNS_CRYPT_VERSION }}.tar.gz
    dest: /opt
    remote_src: yes
  when: dnscrypt_version_command.rc != 0 or DNS_CRYPT_VERSION != dns_crypt_version

- name: Rename folder
  command: mv -vf /opt/linux-x86_64 /opt/dnscrypt-proxy
  when: dnscrypt_version_command.rc != 0 or DNS_CRYPT_VERSION != dns_crypt_version

- name: Remove tar file
  file:
    path: /opt/dnscrypt-proxy-linux_x86_64-{{ DNS_CRYPT_VERSION }}.tar.gz
    state: absent

- name: Copy DNS Crypt configuration
  copy:
    src: dnscrypt-proxy.toml
    dest: /opt/dnscrypt-proxy/dnscrypt-proxy.toml
  notify: Restart DNS Crypt Proxy service

- name: Get service facts
  service_facts:

- name: Install DNS Crypt Proxy service
  command: /opt/dnscrypt-proxy/dnscrypt-proxy -service install
  when: not ansible_facts.services["dnscrypt-proxy.service"] is defined

- name: Start DNS Crypt Proxy service
  service:
    name: dnscrypt-proxy
    state: started
