---

- name: Install HAProxy
  apt:
    pkg:
      - haproxy
    update_cache: yes

- name: Place config file
  copy:
    src: haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg

- name: Start and enable
  service:
    name: haproxy
    state: started
    enabled: yes
