---

- name: Install HAProxy
  apt:
    pkg:
      - haproxy
    update_cache: yes

- name: Place config file
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg

- name: Set stat socket permissions
  file:
    path: /run/haproxy/admin.sock
    mode: 666

- name: Start and enable
  service:
    name: haproxy
    state: started
    enabled: yes
