- name: Check if K3s version is installed
  ansible.builtin.command: k3s --version
  register: k3s_version_command
  ignore_errors: yes
  changed_when: False

- name: set K3s version fact
  set_fact:
    k3s_version: "{{ k3s_version_command.stdout | regex_search(regexp) }}"
  vars:
    regexp: 'v[0-9]+\.[0-9]+\.[0-9]+\+k3s[0-9]'
    cacheable: yes
  when: k3s_version_command.rc == 0

- name: install k3s via official script (first node)
  ansible.builtin.shell: curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ K3S_VERSION }} {{ 'K3S_TOKEN={}'.format(K3S_TOKEN) if K3S_CLUSTER_INIT else '' }} INSTALL_K3S_EXEC="server --disable=traefik {{ '--cluster-init' if K3S_CLUSTER_INIT else '' }} {{ K3S_MASTER_EXTRA_OPTS }}" sh -s -
  when:
    - k3s_version_command.rc != 0 or k3s_version != K3S_VERSION
    - inventory_hostname == K3S_MASTER
  args:
    warn: False

- name: Get K3s token from Master
  command: cat /var/lib/rancher/k3s/server/node-token
  register: k3s_token_command
  when:
    - inventory_hostname == K3S_MASTER
    - not K3S_CLUSTER_INIT
  changed_when: False

- name: install k3s via official script (rest of the nodes)
  ansible.builtin.shell: curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ K3S_VERSION }} K3S_TOKEN='{{ K3S_TOKEN if K3S_CLUSTER_INIT else hostvars[K3S_MASTER]["k3s_token_command"].stdout }}' K3S_URL=https://{{ K3S_MASTER }}:6443 sh -s -
  when:
    - k3s_version_command.rc != 0 or k3s_version != K3S_VERSION
    - inventory_hostname != K3S_MASTER
  args:
    warn: False
