- import_tasks: lcd_base.yml

- name: Copy k8s_stats_lcd.py script
  ansible.builtin.copy:
    src: k8s_stats_lcd/k8s_stats_lcd.py
    dest: /opt/lcd/k8s_stats_lcd.py

- name: setup cron for k8s_stats_lcd.py
  ansible.builtin.cron:
    name: k8s_stats_lcd
    hour: "*/2"
    job: "/opt/lcd/venv/bin/python /opt/lcd/k8s_stats_lcd.py {{k8s_stats_lcd_stats}} -S"
    state: present
    user: root
