---

- name: Disable swap for k8s
  command: swapoff -a

- name: Remove swap from fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- import_tasks: microk8s.yml

- name: Populate Persistent Volume for syncthing
  copy:
    src: config
    dest: /mnt/syncthing-data/config
    force: no

- name: Set permissions for syncthing volume
  file:
    path: /mnt/syncthing-data
    state: directory
    owner: dennis
    group: dennis
    recurse: yes
    force: yes

- name: Set permissions for influxdb volume
  file:
    path: /mnt/influxdb
    state: directory
    owner: '501'
    group: '501'
    recurse: yes
    force: yes

- name: Set permissions for folding-at-home volume
  file:
    path: /mnt/folding-at-home
    state: directory
    owner: '502'
    group: '502'
    recurse: yes
    force: yes

- name: Set permissions for rocketchat mongodb volume
  file:
    path: /mnt/rocketchat-mongodb
    state: directory
    owner: '503'
    group: '503'
    recurse: yes
    force: yes
