---

- name: Check if swap is enabled
  command: swapon --show
  register: swap_files
  changed_when: False

- name: Disable swap for k8s
  command: swapoff -a
  when: swap_files.stdout != ""

- name: Remove swap from fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- import_tasks: microk8s.yml

- name: Populate Persistent Volume for syncthing
  copy:
    src: config
    dest: /mnt/syncthing-data/config
    force: no

- name: Set permissions for syncthing volume
  file:
    path: /mnt/syncthing-data
    state: directory
    owner: dennis
    group: dennis
    recurse: yes
    force: yes

- name: Set permissions for influxdb volume
  file:
    path: /mnt/influxdb
    state: directory
    owner: '501'
    group: '501'
    recurse: yes
    force: yes

- name: Set permissions for mattermost data volume
  file:
    path: /mnt/mattermost-data
    state: directory
    owner: '2000'
    group: '2000'
    recurse: yes
    force: yes

- name: Set permissions for mattermost plugins volume
  file:
    path: /mnt/mattermost-plugins
    state: directory
    owner: '2000'
    group: '2000'
    recurse: yes
    force: yes

- name: Set permissions for code-server volume
  file:
    path: /mnt/code-server
    state: directory
    owner: '503'
    group: '503'
    recurse: yes
    force: yes

- name: Set permissions for bitwarden volume
  file:
    path: /mnt/bitwarden
    state: directory
    owner: '504'
    group: '504'
    recurse: yes
    force: yes
