---

- name: Check if swap is enabled
  command: swapon --show
  register: swap_files
  changed_when: False

- name: Disable swap for k8s
  command: swapoff -a
  when: swap_files.stdout != ""

- name: Remove swap from fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- import_tasks: microk8s.yml

- name: Populate Persistent Volume for syncthing
  copy:
    src: config
    dest: /mnt/data/syncthing-data/config
    force: no
  when:
    - inventory_hostname == K8S_MASTER

- name: Set permissions for syncthing volume
  file:
    path: /mnt/data/syncthing-data
    state: directory
    owner: dennis
    group: dennis
    recurse: yes
    force: yes
  when:
    - inventory_hostname == K8S_MASTER

- name: Set permissions for influxdb volume
  file:
    path: /mnt/data/influxdb
    state: directory
    owner: '501'
    group: '501'
    recurse: yes
    force: yes
  when:
    - inventory_hostname == K8S_MASTER

- name: Set permissions for mattermost data volume
  file:
    path: /mnt/data/mattermost-data
    state: directory
    owner: '2000'
    group: '2000'
    recurse: yes
    force: yes
  when:
    - inventory_hostname == K8S_MASTER

- name: Set permissions for mattermost plugins volume
  file:
    path: /mnt/data/mattermost-plugins
    state: directory
    owner: '2000'
    group: '2000'
    recurse: yes
    force: yes
  when:
    - inventory_hostname == K8S_MASTER
