---

- name: Disable swap for k8s
  command: swapoff -a

- name: Remove swap from fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- import_tasks: microk8s.yml

- name: Populate Persistent Volume for statping
  copy:
    src: statping-app-data
    dest: /mnt/
    force: no
