---

- name: Install software-properties-common
  apt:
    pkg: software-properties-common
    update_cache: yes

- name: Add Repository
  apt_repository:
    repo: ppa:certbot/certbot

- name: Install certbot
  apt:
    pkg: certbot
    update_cache: yes

- name: print cert setup command
  debug:
    msg:
      - "certbot is installed. You need to run the following manually and set the DNS TXT record for _acme-challenge.{{ MY_DOMAIN }}"
      - "certbot certonly --manual --agree-tos --preferred-challenges dns-01 -d {{ MY_DOMAIN }} -d *.{{ MY_DOMAIN }} -m {{ MY_EMAIL }}"
