---

- import_tasks: telegraf.yml
  become: yes

- import_tasks: dns_crypt.yml
  become: yes
  when: '"dns_crypt" in ADD_ROLES'

- import_tasks: lets_encrypt.yml
  become: yes
  when: '"nginx" in ADD_ROLES'

- import_tasks: nginx.yml
  become: yes
  when: '"nginx" in ADD_ROLES'

- import_tasks: fail2ban.yml
  become: yes
  when: '"nginx" in ADD_ROLES'

- import_tasks: k8s_node.yml
  become: yes
  when: '"k8s_node" in ADD_ROLES'
