- import_tasks: oracle_iptables.yml
  become: yes
  when: "'oracle' in group_names"

- import_tasks: lets_encrypt.yml
  become: yes
  when: '"nginx" in ADD_ROLES'

- import_tasks: nginx.yml
  become: yes
  when: '"nginx" in ADD_ROLES'

- import_tasks: nginx_stats_lcd.yml
  when: '"nginx_stats_lcd" in ADD_ROLES'
  become: yes

- import_tasks: nginx_blink.yml
  when: '"nginx_blink" in ADD_ROLES'
  become: yes

- import_tasks: prereq.yml
  become: yes
  when: '"k3s_node" in ADD_ROLES'

- import_tasks: k3s.yml
  become: yes
  when: '"k3s_node" in ADD_ROLES'

- import_tasks: node_stats_lcd.yml
  become: yes
  when: '"node_stats_lcd" in ADD_ROLES'

- import_tasks: nfs.yml
  become: yes
  when: '"nfs" in ADD_ROLES'

- import_tasks: pihole.yml
  become: yes
  when: '"pihole" in ADD_ROLES'

- import_tasks: pihole_stats_lcd.yml
  become: yes
  when: '"pihole_stats_lcd" in ADD_ROLES'

- import_tasks: pihole_blink.yml
  become: yes
  when: '"pihole_blink" in ADD_ROLES'
