- name: add my pubkey to authorized_keys
  authorized_key:
    user: '{{ ansible_user }}'
    key: '{{ item }}'
    exclusive: yes
  with_items:
    - 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINuZWvtBoFxPP2nv6N13jtO3EazntuIHsaiH6Q1DbbKF homelab'

- name: Disable password ssh login
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication yes'
    line: PasswordAuthentication no
  become: true
  notify: Restart sshd service

- name: Place logrotate conf
  ansible.builtin.copy:
    src: logrotate.conf
    dest: /etc/logrotate.conf
    mode: 0644
  become: true

- import_tasks: telegraf.yml
  become: true

- import_tasks: oracle_iptables.yml
  become: true
  when: "'oracle' in group_names"

- import_tasks: nginx.yml
  become: true
  when: '"nginx" in ADD_ROLES'

- import_tasks: nginx_stats_lcd.yml
  when: '"nginx_stats_lcd" in ADD_ROLES'
  become: true

- import_tasks: nginx_blink.yml
  when: '"nginx_blink" in ADD_ROLES'
  become: true

- import_tasks: prereq.yml
  become: true
  when: '"k3s_node_control" in ADD_ROLES or "k3s_node_worker" in ADD_ROLES'

- import_tasks: k3s.yml
  become: true
  when: '"k3s_node_control" in ADD_ROLES or "k3s_node_worker" in ADD_ROLES'

- import_tasks: node_stats_lcd.yml
  become: true
  when: '"node_stats_lcd" in ADD_ROLES'

- import_tasks: pihole.yml
  become: true
  when: '"pihole" in ADD_ROLES'

- import_tasks: pihole_stats_lcd.yml
  become: true
  when: '"pihole_stats_lcd" in ADD_ROLES'

- import_tasks: pihole_blink.yml
  become: true
  when: '"pihole_blink" in ADD_ROLES'

- import_tasks: k8s_stats_lcd.yml
  when: '"k8s_stats_lcd" in ADD_ROLES'
  become: true
