---

- name: install snap
  apt:
    name: snapd
    update_cache: yes

- name: Install MicroK8s
  snap:
    name: microk8s
    classic: yes
    channel: "{{ MICROK8S_CHANNEL }}"

- name: Get snap refresh schedule
  shell: 'snap refresh --time | grep "timer: {{ MICROK8S_SNAP_REFRESH_TIME}}"'
  register: snap_refresh_time_command
  changed_when: False
  ignore_errors: yes

- name: Update snaps refresh time
  command: snap set system refresh.timer={{ MICROK8S_SNAP_REFRESH_TIME }}
  when: snap_refresh_time_command.rc != 0

- name: Adding user {{ USER }} to microk8s group
  user:
    name: "{{ USER }}"
    groups: microk8s
    append: yes

- name: Get enabled MicroK8s addons
  shell: microk8s status --format short | grep enabled | awk -F ':' '{print $1}'
  register: microk8s_enabled_addons
  when: inventory_hostname == K8S_MASTER
  changed_when: False

- name: Enable MicroK8s addons
  command: microk8s enable {{ item }}
  loop: "{{ MICROK8S_ADDONS }}"
  when:
    - inventory_hostname == K8S_MASTER
    - item not in microk8s_enabled_addons.stdout_lines
    - item != 'metallb'

- name: Enable metallb MicroK8s addon
  command: microk8s enable metallb
  args:
    stdin: "{{ METALLB_IP_RANGE }}"
  when:
    - inventory_hostname == K8S_MASTER
    - '"metallb" in MICROK8S_ADDONS'
    - '"metallb" not in microk8s_enabled_addons.stdout_lines'

# https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/
# https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file
- name: Copy kubelet config
  copy:
    src: kubelet.conf
    dest: /etc/kubelet.conf
  notify: Restart kubelet service
