- name: Install NFS Server
  ansible.builtin.apt:
    pkg: nfs-kernel-server
    update_cache: yes

- name: Create /mnt/data
  ansible.builtin.file:
    path: /mnt/data
    state: directory

- name: place exports file
  ansible.builtin.copy:
    src: nfs/exports
    dest: /etc/exports
  notify: Update Exports

- name: Set permissions for squash root nfs clients
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    owner: nobody
    group: nogroup
    recurse: yes
    force: yes
  with_items:
    - /mnt/data/freshrss-data
    - /mnt/data/owncast-data
    - /mnt/data/dynamic

- name: Populate Persistent Volume for syncthing
  ansible.builtin.copy:
    src: syncthing/config
    dest: /mnt/data/syncthing-data/config
    force: no
    owner: '1000'
    group: '1000'

- name: Set permissions for user 1000 owned dirs
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    owner: '1000'
    group: '1000'
    recurse: yes
    force: yes
  with_items:
    - /mnt/data/syncthing-data
    - /mnt/data/syncthing-data/jellyfin-data
    - /mnt/data/prometheus-data/prometheus-db
