---

- name: Install NFS Server
  apt:
    pkg:
      - nfs-kernel-server
    update_cache: yes

- name: Create /mnt/data
  file:
    path: /mnt/data
    state: directory

- name: place exports file
  copy:
    src: exports
    dest: /etc/exports
  notify: Update Exports

- name: Set permissions for bitwarden volume
  file:
    path: /mnt/data/bitwarden
    state: directory
    owner: nobody
    group: nogroup
    recurse: yes
    force: yes

- name: Set permissions for concourse postgresql volume
  file:
    path: /mnt/data/concourse-postgresql
    state: directory
    owner: '1001'
    group: '1001'
    recurse: yes
    force: yes

- name: Set permissions for concourse workers tmp volume
  file:
    path: /mnt/data/concourse-tmp
    state: directory
    owner: nobody
    group: nogroup
    recurse: yes
    force: yes

- name: Populate Persistent Volume for syncthing
  copy:
    src: config
    dest: /mnt/data/syncthing-data/config
    force: no
    owner: '1000'
    group: '1000'

- name: Set permissions for syncthing volume
  file:
    path: /mnt/data/syncthing-data
    state: directory
    owner: '1000'
    group: '1000'
    recurse: yes
    force: yes

- name: Set permissions for influxdb volume
  file:
    path: /mnt/data/influxdb
    state: directory
    owner: '501'
    group: '501'
    recurse: yes
    force: yes

- name: Set permissions for mattermost data volume
  file:
    path: /mnt/data/mattermost-data
    state: directory
    owner: '2000'
    group: '2000'
    recurse: yes
    force: yes

- name: Set permissions for mattermost plugins volume
  file:
    path: /mnt/data/mattermost-plugins
    state: directory
    owner: '2000'
    group: '2000'
    recurse: yes
    force: yes

- name: Set permissions for mattermost mysql volume
  file:
    path: /mnt/data/mattermost-mysql
    state: directory
    owner: '2001'
    group: '2001'
    recurse: yes
    force: yes

- name: Set permissions for wireguard volume
  file:
    path: /mnt/data/wireguard
    state: directory
    owner: nobody
    group: nogroup
    recurse: yes
    force: yes
