---

- name: Install NFS Server
  apt:
    pkg:
      - nfs-kernel-server
    update_cache: yes

- name: Create /mnt/data
  file:
    path: /mnt/data
    state: directory

- name: place exports file
  copy:
    src: exports
    dest: /etc/exports
  notify: Update Exports
