- import_tasks: lcd_base.yml

- name: Copy nginx_stats_lcd.py script
  copy:
    src: nginx_stats_lcd/nginx_stats_lcd.py
    dest: /opt/lcd/nginx_stats_lcd.py
  notify: Restart nginx_stats_lcd service

- name: Copy nginx_stats_lcd service
  copy:
    src: nginx_stats_lcd/nginx_stats_lcd.service
    dest: /etc/systemd/system/nginx_stats_lcd.service

- name: Start and enable nginx_stats_lcd service
  service:
    name: nginx_stats_lcd
    state: started
    enabled: yes
