- name: Install Nginx
  ansible.builtin.apt:
    pkg: nginx
    update_cache: yes

- name: remove default site
  ansible.builtin.file:
    dest: /etc/nginx/sites-enabled/default
    state: absent

- name: update file descriptor limits
  ansible.builtin.lineinfile:
    path: /etc/security/limits.conf
    line: '{{ item }}'
  with_items:
    - nginx       soft    nofile  30000
    - nginx       hard    nofile  50000
  notify: Restart nginx service
  become: true

- name: Place nginx conf file
  ansible.builtin.template:
    src: nginx/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: Restart nginx service

- name: Test nginx conf
  ansible.builtin.command: nginx -t
  become: true
  changed_when: False

- name: Start and enable
  service:
    name: nginx
    state: started
    enabled: yes

- name: Chmod on logrorate
  ansible.builtin.file:
    dest: /etc/logrotate.d/nginx
    mode: 0644
