---

- name: Install i2c dependencies tools
  apt:
    pkg:
      - python3-pip
      - i2c-tools
    update_cache: yes

- name: Install setuptools
  pip:
    name: setuptools

- name: Install i2c pip dependencies
  pip:
    name:
      - RPLCD
      - smbus2

- name: Copy nginx_stats_lcd.py script
  copy:
    src: nginx_stats_lcd.py
    dest: /opt/nginx_stats_lcd.py

- name: Copy nginx_stats_lcd service
  copy:
    src: nginx_stats_lcd.service
    dest: /etc/systemd/system/nginx_stats_lcd.service

- name: Start and enable nginx_stats_lcd serivce
  service:
    name: nginx_stats_lcd
    state: started
    enabled: yes
