- name: Remove FORWARD Reject
  ansible.builtin.lineinfile:
    path: /etc/iptables/rules.v4
    regex: '^-A FORWARD -j REJECT --reject-with icmp-host-prohibited$'
    state: absent
  when: '"k3s_node" in ADD_ROLES'
  register: oip_forward

- name: open oracle VM port 6443
  ansible.builtin.lineinfile:
    path: /etc/iptables/rules.v4
    insertbefore: '^-A INPUT -j REJECT --reject-with icmp-host-prohibited$'
    line: -A INPUT -p tcp -m state --state NEW -m tcp --dport 6443 -j ACCEPT
  when:
    - '"k3s_node" in ADD_ROLES'
    - inventory_hostname == K3S_MASTER
  register: oip_k8s

- name: open oracle VM port 80 to subnet
  ansible.builtin.lineinfile:
    path: /etc/iptables/rules.v4
    insertbefore: '^-A INPUT -j REJECT --reject-with icmp-host-prohibited$'
    line: -A INPUT -p tcp -s 10.0.0.0/16 --dport 80 -j ACCEPT
  when: '"k3s_node" in ADD_ROLES'
  register: oip_http

- name: open oracle vm port 53
  ansible.builtin.lineinfile:
    path: /etc/iptables/rules.v4
    insertbefore: '^-A INPUT -j REJECT --reject-with icmp-host-prohibited$'
    line: -A INPUT -p udp -m state --state NEW -m udp --dport 53 -j ACCEPT
  when: '"pihole" in ADD_ROLES'
  register: oip_dns

- name: Update Iptables
  shell: /usr/sbin/iptables-restore < /etc/iptables/rules.v4
  when: oip_forward.changed or oip_k8s.changed or oip_http.changed or oip_dns.changed
