- name: open oracle VM port 80
  ansible.builtin.lineinfile:
    path: /etc/iptables/rules.v4
    insertbefore: '^-A INPUT -j REJECT --reject-with icmp-host-prohibited$'
    line: -A INPUT -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT
  when: '"dc_services" in ADD_ROLES'
  register: oip_http

- name: open oracle VM port 443
  ansible.builtin.lineinfile:
    path: /etc/iptables/rules.v4
    insertbefore: '^-A INPUT -j REJECT --reject-with icmp-host-prohibited$'
    line: -A INPUT -p tcp -m state --state NEW -m tcp --dport 443 -j ACCEPT
  when: '"dc_services" in ADD_ROLES'
  register: oip_https

- name: open oracle vm port 53
  ansible.builtin.lineinfile:
    path: /etc/iptables/rules.v4
    insertbefore: '^-A INPUT -j REJECT --reject-with icmp-host-prohibited$'
    line: -A INPUT -p udp -m state --state NEW -m udp --dport 53 -j ACCEPT
  when: '"pihole" in ADD_ROLES'
  register: oip_dns

- name: Update Iptables
  shell: /usr/sbin/iptables-restore < /etc/iptables/rules.v4
  when: oip_http.changed or oip_https.changed or oip_dns.changed
