- name: Install unbound
  apt:
    name: unbound
    update_cache: yes

- name: Setup unbound conf for pihole
  copy:
    src: unbound_pihole_conf
    dest: /etc/unbound/unbound.conf.d/pi-hole.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart unbound

- name: Check if pihole is installed
  command: pihole
  register: pihole_command
  ignore_errors: yes
  changed_when: False

- name: "Download Pi-Hole installer"
  get_url:
    url: https://install.pi-hole.net
    dest: /tmp/install-pihole.sh
    mode: 0740
  when: pihole_command.rc != 0

- name: Create pihole configuration directory
  file:
    name: /etc/pihole
    state: directory
    owner: pihole
    group: pihole
    mode: 0755
  when: pihole_command.rc != 0

- name: Create pihole configuration
  template:
    src: pihole_setupVars.conf
    dest: /etc/pihole/setupVars.conf
    owner: root
    group: root
    mode: 0644
  when: pihole_command.rc != 0

- name: Install Pi-Hole
  shell: "/tmp/install-pihole.sh --unattended"
  when: pihole_command.rc != 0

- name: Setup crontab config
  copy:
    src: pihole_cron_config
    dest: /etc/cron.d/pihole
    owner: root
    group: root
    mode: 0644
