- name: Check if pihole is installed
  ansible.builtin.command: pihole
  register: pihole_command
  ignore_errors: yes
  changed_when: False

- name: "Download Pi-Hole installer"
  ansible.builtin.get_url:
    url: https://install.pi-hole.net
    dest: /tmp/install-pihole.sh
    mode: 0740
  when: pihole_command.rc != 0

- name: Create pihole configuration directory
  ansible.builtin.file:
    name: /etc/pihole
    state: directory
    owner: root
    group: root
    mode: 0755
  when: pihole_command.rc != 0

- name: Create pihole configuration
  ansible.builtin.template:
    src: pihole/pihole_setupVars.conf.j2
    dest: /etc/pihole/setupVars.conf
    owner: root
    group: root
    mode: 0644
  when: pihole_command.rc != 0

- name: Install Pi-Hole
  ansible.builtin.shell: "/tmp/install-pihole.sh --unattended"
  when: pihole_command.rc != 0

- name: Setup crontab config
  ansible.builtin.copy:
    src: pihole/pihole_cron_config
    dest: /etc/cron.d/pihole
    owner: root
    group: root
    mode: 0644

- name: Install unbound
  ansible.builtin.apt:
    name: unbound
    update_cache: yes
  register: install_unbound

- name: Setup unbound conf for pihole
  ansible.builtin.copy:
    src: pihole/unbound_pihole_conf
    dest: /etc/unbound/unbound.conf.d/pi-hole.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart unbound

- name: restart Unbound
  ansible.builtin.service:
    name: unbound
    state: restarted
  when: install_unbound.changed
