---

- name: Install bc
  apt:
    pkg: bc
    update_cache: yes

- name: Check if blink1-tool version is installed
  command: blink1-tool --version
  register: blink_version_command
  ignore_errors: yes
  changed_when: False

- name: set blink1-tool version fact
  set_fact:
    blink_version: "{{ blink_version_command.stdout | regex_search(regexp) }}"
  vars:
    regexp: '[0-9]+\.[0-9]+\.[0-9]+'
    cacheable: yes
  when: blink_version_command.rc == 0

- name: Download blink1-tool armv6l
  unarchive:
    src: https://github.com/todbot/blink1-tool/releases/download/v{{ BLINK_VERSION }}/blink1-tool-v{{ BLINK_VERSION }}-linux-armv7l.zip
    dest: /tmp
    remote_src: yes
  when:
    - ansible_architecture == 'armv6l'
    - blink_version_command.rc != 0 or BLINK_VERSION != blink_version

- name: Install blink1-tool
  command: mv -f /tmp/blink1-tool /usr/local/bin/blink1-tool
  when:
    - blink_version_command.rc != 0 or BLINK_VERSION != blink_version


- name: place blink script
  copy:
    src: pihole_status_blink.sh
    dest: /opt/pihole_status_blink.sh
    owner: root
    group: root
    mode: '770'

- name: place service conf file
  copy:
    src: pihole-status-blink.service
    dest: /etc/systemd/system/pihole-status-blink.service

- name: Start and enable
  service:
    name: pihole-status-blink.service
    state: started
    enabled: yes
