- name: Check if swap is disabled
  ansible.builtin.command: swapon --show
  register: swap_files
  changed_when: False

- name: Disable swap for k8s
  ansible.builtin.command: swapoff -a
  when: swap_files.stdout != ""

- name: Remove swap from fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Install k3s prereq tools
  ansible.builtin.apt:
    pkg:
      - nfs-common
      - apparmor-utils
  become: true
  when: "'baremetal' in group_names"
