- name: Check if swap is disabled
  ansible.builtin.command: swapon --show
  register: swap_files
  changed_when: False

- name: Disable swap for k8s
  ansible.builtin.command: swapoff -a
  when: swap_files.stdout != ""

- name: Remove swap from fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Install NFS common
  ansible.builtin.apt:
    name: nfs-common
    update_cache: yes
  when: "'baremetal' in group_names"
