---

- name: Check if Bat version is installed
  shell: bat --version | awk '{print $2}'
  register: bat_version
  ignore_errors: yes

- name: Download Bat
  unarchive:
    src: https://github.com/sharkdp/bat/releases/download/v{{ BAT_VERSION }}/bat-v{{ BAT_VERSION }}-x86_64-unknown-linux-gnu.tar.gz
    dest: /tmp
    remote_src: yes
  when: bat_version.rc != 0 or bat_version.stdout != BAT_VERSION

- name: Install Bat
  command: mv -f /tmp/bat-v{{ BAT_VERSION }}-x86_64-unknown-linux-gnu/bat /usr/local/bin/bat
  when: bat_version.rc != 0 or bat_version.stdout != BAT_VERSION
  become: yes

- name: Set execute permissions for bat
  file:
    path: /usr/local/bin/k9s
    mode: u+x
    modification_time: preserve
    access_time: preserve
  become: yes
