---

- name: Install my bash_profile
  copy:
    src: bash_profile
    dest: /home/dennis/.bash_profile

- name: Install tools
  apt:
    pkg:
      - curl
      - make
      - screen
    update_cache: yes
  become: yes

- name: Get netplan files
  command: find /etc/netplan/ -type f -name "*.yaml"
  register: netplan_confs
  become: yes

- name: Update DNS nameservers
  replace:
    path: "{{ item }}"
    regexp: 'addresses: [.*].*$'
    replace: "addresses: [{{ PIHOLE_SERVER_IP }}, 8.8.8.8, 8.8.4.4]"
  with_items: "{{ netplan_confs.stdout_lines }}"
  become: yes
  notify: Apply Netplan
