---

- name: Install my bash_profile
  copy:
    src: bash_profile
    dest: /home/dennis/.bash_profile

- name: add my pubkey to known_hosts
  authorized_key:
    user: dennis
    key: '{{ item }}'
  with_items:
    - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCsVI8KsVO0yr+E3/Imc6K94wdsLTXk5xXMT8qEuZ3brsvWLVtbVbgDdPppWY5r/XzS6pPvyCAvcAg04fuBldrJOMNEQqSUzDe7Vz8EBbfUzHa6H3LIVPxhJ8uCa6+iwgAcc6nSU5NxqQkDbySRsE9MnfAHONplcjh6w6K1Ds5dPefddlKvZ/whl30EbRYwz53/vHck3t0xClhB4KsqIqLabXLmpW+8ObD0WkEARLirFNXl+UYQiDkmZYKSYq6cQHvpEeifIWZGdt61PolLiKZDoF3o51lnlWgx2C3XSnbE/cwI1JYZ84vpCRou4knKNVH9q0aTTFchzg1kiUt8qkgAyuYxlvgK6v8Aq6j9zpqcb+mhnswH2jhiCvKXemczFqTdXyif/eeHhjhvXFla2ePnr7cB/1emyuzWc4mmmZeaqYK3Yz4j/rkZk0w3HkG3FbBvvAYc9JBnpBS2/WwQfXb4h+6NZ/80J07wl/7qE/HxE15qvwSE31BgvJi+S9SvfxuO8oq+EZwSz6ngvgR2JZH++XoEZu9iLe25DF+MlIwpfo32lOeE/R/eFIbaZQrNiA7KL7vUctu/jH6pdR7BMnHUHYCnlU7UjrafI5Cn7XZQgqEB2JYZWN9ZAiaLi9irrMWdTNSU7t2Dsrpuv8ngJkLHJW+qYDuKCN9w14O4Uximew== my_desktop"
    - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDgQsNsmdhcDiRQLi1T6EuFpTjuOmvNWk4tYuGMdp6AeTYLuFf81kuCF2nJ978uTaiq1dLruhLmevTSrtCizK5ncD7LaNq+B07ufYm8MfTQoMAy1i2WhpNr3eR7BoTasyWC3+Y01/TSXN6oE2KGB6AzsS1WUbwSXMjzZSlXfqUE0dZ5sOzBw/mVMh5ds93Lsw+f5nNqdTFM+98C+oF2axREaGOEG+GheUUa6qJEEBgSK3gDh4o/FSaGC4+mibqB+Wn/sBRedd+5kT8NPRDDPNYrARAynv7zhmoF73YgfwxaT9tNVDvgkCoJs4mjKWkb2i+E+qzinUs1I3TVs0DbYeRpslgZl5iz73iQhs3JQ26mZg22OrjJSJITKnfD3gcJEAxlp8XLnV2oo3cpbuwxLDN6Exf0vBP396ZJi+h62JaoU95SXptgLr8htHUpzrsTYmFavtgxkapDN44n4+WW82tdW3fctVKIN5dC7M0j4Oeil/+tBv9R5TixAU7NKiwWQZWCKXGstL6PmdyRq0+sLPZu4H0OgbuBU9Ybt+Z+lc4HJix6q6/+aFnHBWy96XbDzeh+66v1qjJQQKiq1CvQkFdOhIWFfOpYByDdoDVC6jJp2xszf5FZTdKNlYQKUDTnr8DMtJJnTzqyChtw0rASKhBG8/kt1zM8CJlwDicpJOEN/Q== surfacego2"

- name: Install tools
  apt:
    pkg:
      - curl
      - make
      - screen
      - resolvconf
    update_cache: yes
  become: yes

- name: Place resolve conf
  template:
    src: resolvconf_head.j2
    dest: /etc/resolvconf/resolv.conf.d/head
  become: yes
  notify: Restart resolvconf

- name: Start and enable resolvconf
  service:
    name: resolvconf
    state: started
    enabled: yes
  become: yes

- import_tasks: bat.yml

- name: Disable sleep on lid close
  lineinfile:
    path: /etc/systemd/logind.conf
    line: '{{ item }}'
  with_items:
    - HandleLidSwitch=ignore
    - HandleLidSwitchDocked=ignore
  notify: Restart systemd-logind
  become: yes
