---

- name: Set default incoming policies
  ufw:
    default: deny
    direction: incoming

- name: Set default outgoing policies
  ufw:
    default: allow
    direction: outgoing

- name: Allow http and https
  ufw:
    rule: allow
    port: '{{ item }}'
    proto: tcp
  with_items:
    - '80'
    - '443'
  when: '"nginx" in ADD_ROLES'

- name: Allow Wireguard
  ufw:
    rule: allow
    port: '51820'
    proto: udp
  when: '"nginx" in ADD_ROLES'

- name: Allow all access from LAN and wireguard and enable
  ufw:
    rule: allow
    src: '{{ item }}'
    state: enabled
  with_items:
    - 192.168.1.0/24
    - 192.168.2.0/24
    - 10.44.0.0/24 # Wireguard
    - 10.1.66.0/24 # K8s pods
