---

- name: Install unattended-upgrades
  apt:
    pkg: unattended-upgrades
    update_cache: yes
  become: yes

- name: Place conf
  template:
    src: 50unattended-upgrades
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
  notify: Restart unattended-upgrades

- name: Start unattended-upgrades service
  service:
    name: unattended-upgrades
    state: started
    enabled: yes
