- import_tasks: unattended-upgrades.yml
  become: true

- import_tasks: telegraf.yml
  become: true

- name: Restart sshd service
  service:
    name: sshd
    state: restarted
  become: true

- name: Restart systemd-logind service
  service:
    name: systemd-logind
    state: restarted
  become: true
