---

- name: Restart resolvconf
  service:
    name: resolvconf
    state: restarted
  become: yes

- name: Restart systemd-logind
  service:
    name: systemd-logind
    state: restarted
  become: yes

- name: Restart host
  reboot:
    reboot_timeout: 60
  become: yes
