---

- name: Disable swap for k8s
  command: swapoff -a
  become: yes

- name: Remove swap from fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'
  become: yes

- import_tasks: microk8s.yml
  become: yes
