- name: Install Canonical Livepatch
  snap:
    name: canonical-livepatch
  when:
    - ansible_distribution == 'Ubuntu'
    - install_canonical_livepatch|default(false)|bool

- name: Check if Canonical Livepatch is Enabled
  ansible.builtin.command: canonical-livepatch status
  register: livepatch_status
  ignore_errors: yes
  changed_when: False
  when:
    - ansible_distribution == 'Ubuntu'
    - install_canonical_livepatch|default(false)|bool

- name: Enable Canonical Livepatch
  ansible.builtin.command: "canonical-livepatch enable {{ CANONICAL_LIVEPATCH_KEY }}"
  when:
    - ansible_distribution == 'Ubuntu'
    - install_canonical_livepatch|default(false)|bool
    - "'Machine is not enabled' in livepatch_status.stdout"
