- name: Install my bash_profile
  ansible.builtin.template:
    src: bash_profile
    dest: /home/{{ ansible_user }}/.bash_profile

- name: add my pubkey to authorized_keys
  authorized_key:
    user: '{{ ansible_user }}'
    key: '{{ item }}'
  with_items:
    - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCsVI8KsVO0yr+E3/Imc6K94wdsLTXk5xXMT8qEuZ3brsvWLVtbVbgDdPppWY5r/XzS6pPvyCAvcAg04fuBldrJOMNEQqSUzDe7Vz8EBbfUzHa6H3LIVPxhJ8uCa6+iwgAcc6nSU5NxqQkDbySRsE9MnfAHONplcjh6w6K1Ds5dPefddlKvZ/whl30EbRYwz53/vHck3t0xClhB4KsqIqLabXLmpW+8ObD0WkEARLirFNXl+UYQiDkmZYKSYq6cQHvpEeifIWZGdt61PolLiKZDoF3o51lnlWgx2C3XSnbE/cwI1JYZ84vpCRou4knKNVH9q0aTTFchzg1kiUt8qkgAyuYxlvgK6v8Aq6j9zpqcb+mhnswH2jhiCvKXemczFqTdXyif/eeHhjhvXFla2ePnr7cB/1emyuzWc4mmmZeaqYK3Yz4j/rkZk0w3HkG3FbBvvAYc9JBnpBS2/WwQfXb4h+6NZ/80J07wl/7qE/HxE15qvwSE31BgvJi+S9SvfxuO8oq+EZwSz6ngvgR2JZH++XoEZu9iLe25DF+MlIwpfo32lOeE/R/eFIbaZQrNiA7KL7vUctu/jH6pdR7BMnHUHYCnlU7UjrafI5Cn7XZQgqEB2JYZWN9ZAiaLi9irrMWdTNSU7t2Dsrpuv8ngJkLHJW+qYDuKCN9w14O4Uximew== my_desktop'
    - 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILvkVEszd/+8vzRQtynb1HsE2keFWcAqI8gRRodboLB/ surface3'
    - 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDSO0l5TQOEQ60qI4AtqREfm0aklRn/MiIfr2nBm5p+0 predator'

- name: Disable password ssh login
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication yes'
    line: PasswordAuthentication no
  become: yes
  notify: Restart sshd service

- name: Place logrotate conf
  ansible.builtin.copy:
    src: logrotate.conf
    dest: /etc/logrotate.conf
    mode: 0644
  become: yes

- name: Symlink python -> python3
  ansible.builtin.file:
    src: /usr/bin/python3
    dest: /usr/bin/python
    state: link
  become: yes

- name: Install tools
  ansible.builtin.apt:
    pkg:
      - curl
      - dnsutils
      - iotop
      - screen
      - resolvconf
      - procinfo
      - traceroute
    update_cache: yes
  become: yes

- name: Place resolve conf
  ansible.builtin.template:
    src: resolvconf_head.j2
    dest: /etc/resolvconf/resolv.conf.d/head
  become: yes
  notify: Restart resolvconf service

- name: update resolvconf
  ansible.builtin.command: sudo resolvconf -u
  become: yes

- name: Start and enable resolvconf
  service:
    name: resolvconf
    state: started
    enabled: yes
  become: yes

- name: Disable sleep on lid close
  ansible.builtin.lineinfile:
    path: /etc/systemd/logind.conf
    line: '{{ item }}'
  with_items:
    - HandleLidSwitch=ignore
    - HandleLidSwitchDocked=ignore
  notify: Restart systemd-logind service
  become: yes

- name: Place rc.local
  ansible.builtin.copy:
    src: rc.local
    dest: /etc/rc.local
    owner: root
    group: root
    mode: 0777
  notify: Restart host
  become: yes

- import_tasks: live-patch.yml
  become: yes

- import_tasks: unattended-upgrades.yml
  become: yes

- import_tasks: telegraf.yml
  become: yes
  when: "'oracle' not in group_names"
