- name: Install my bash_profile
  copy:
    src: bash_profile
    dest: /home/{{ USER }}/.bash_profile

- name: add my pubkey to authorized_keys
  authorized_key:
    user: '{{ USER }}'
    key: '{{ item }}'
  with_items:
    - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCsVI8KsVO0yr+E3/Imc6K94wdsLTXk5xXMT8qEuZ3brsvWLVtbVbgDdPppWY5r/XzS6pPvyCAvcAg04fuBldrJOMNEQqSUzDe7Vz8EBbfUzHa6H3LIVPxhJ8uCa6+iwgAcc6nSU5NxqQkDbySRsE9MnfAHONplcjh6w6K1Ds5dPefddlKvZ/whl30EbRYwz53/vHck3t0xClhB4KsqIqLabXLmpW+8ObD0WkEARLirFNXl+UYQiDkmZYKSYq6cQHvpEeifIWZGdt61PolLiKZDoF3o51lnlWgx2C3XSnbE/cwI1JYZ84vpCRou4knKNVH9q0aTTFchzg1kiUt8qkgAyuYxlvgK6v8Aq6j9zpqcb+mhnswH2jhiCvKXemczFqTdXyif/eeHhjhvXFla2ePnr7cB/1emyuzWc4mmmZeaqYK3Yz4j/rkZk0w3HkG3FbBvvAYc9JBnpBS2/WwQfXb4h+6NZ/80J07wl/7qE/HxE15qvwSE31BgvJi+S9SvfxuO8oq+EZwSz6ngvgR2JZH++XoEZu9iLe25DF+MlIwpfo32lOeE/R/eFIbaZQrNiA7KL7vUctu/jH6pdR7BMnHUHYCnlU7UjrafI5Cn7XZQgqEB2JYZWN9ZAiaLi9irrMWdTNSU7t2Dsrpuv8ngJkLHJW+qYDuKCN9w14O4Uximew== my_desktop'
    - 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBYUs8i6hhcSTT8mTDuByqSoznBrn9zfMr85XLw5ixKj surface2'

# - name: remove old key
#   authorized_key:
#     user: '{{ USER }}'
#     key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCsmibbw0jcyLi2eXaUsWp7r+DyuMCVz6jDy02yuSTHKiS7UkwPQO6YqdOQoOzC/HwcAFGXJAPgJxOe7L3syeKMf8rqVRTByr800Acss+Y24oGzlRJrD7TNg/ILP+hY2HBpjaXVaXYXfHgyWbVEIhIUo96zLALV51CiNfbKotvy9emHdV/+DrEh6UTMFRaXghXrM0Nf93HJlJLG6APSpst2+agtAYv8yhJh/CTy9mHXWHhsmc2HNW5aqSozklLbR6horcXtzQ86d7/R4sCk+21nc5b/T9vQSMv/HZaC1sWMv+xh40uH3NzkIIP7BQYhZZNKPSztBrX/UCU/eFc/VJL7eRSKmghgXXN728TWBZ0zMl+c2xRNZUSa8jWo2GlnwAQtTdkJt+KMrSv7+PAooAVGs0eOjjWTi39l0TRmUt9krBfWFnfEAv17h7Uy+OlGuU5U5SoWpRgdp1G4AnKzzagmc/E+AP4pR5sfwT2oiAiSoI1IKodzofZ2ROHraKRt+6ag5t8sHBkl+9PhSMh6SZXJZyh2y/Ca9aZYVmLuD0Dwkt9hchPtEYIIqAKzfa2M7DAHoYsMgndrmSG03VCzQetwlMbu7ItOyQzAVRdPnTTleyD46C1Q/+i8qeSO9KxGO/fVhrY9kdEVD1NYjwdfCShuEuuwB3vmI5npVv2bSC9t2Q== gaming_laptop'
#     state: absent

- name: Disable password ssh login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication yes'
    line: PasswordAuthentication no
  become: yes
  notify: Restart sshd service

- name: Place logrotate conf
  copy:
    src: logrotate.conf
    dest: /etc/logrotate.conf
    mode: 0644
  become: yes

- name: Symlink python -> python3
  file:
    src: /usr/bin/python3
    dest: /usr/bin/python
    state: link
  become: yes

- name: Install tools
  apt:
    pkg:
      - curl
      - dnsutils
      - iotop
      - screen
      - resolvconf
      - procinfo
      - traceroute
    update_cache: yes
  become: yes

- name: Place resolve conf
  template:
    src: resolvconf_head.j2
    dest: /etc/resolvconf/resolv.conf.d/head
  become: yes
  notify: Restart resolvconf service

- name: Start and enable resolvconf
  service:
    name: resolvconf
    state: started
    enabled: yes
  become: yes

- name: Disable sleep on lid close
  lineinfile:
    path: /etc/systemd/logind.conf
    line: '{{ item }}'
  with_items:
    - HandleLidSwitch=ignore
    - HandleLidSwitchDocked=ignore
  notify: Restart systemd-logind service
  become: yes

- name: Place rc.local
  copy:
    src: rc.local
    dest: /etc/rc.local
    owner: root
    group: root
    mode: 0777
  notify: Restart host
  become: yes

- import_tasks: unattended-upgrades.yml
  become: yes

- import_tasks: telegraf.yml
  become: yes
