- name: Install my bash_profile
  ansible.builtin.template:
    src: bash_profile
    dest: /home/{{ ansible_user }}/.bash_profile

- name: add my pubkey to authorized_keys
  authorized_key:
    user: '{{ ansible_user }}'
    key: '{{ item }}'
    exclusive: yes
  with_items:
    - 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINuZWvtBoFxPP2nv6N13jtO3EazntuIHsaiH6Q1DbbKF homelab'

- name: Disable password ssh login
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication yes'
    line: PasswordAuthentication no
  become: yes
  notify: Restart sshd service

- name: Place logrotate conf
  ansible.builtin.copy:
    src: logrotate.conf
    dest: /etc/logrotate.conf
    mode: 0644
  become: yes

- name: Symlink python -> python3
  ansible.builtin.file:
    src: /usr/bin/python3
    dest: /usr/bin/python
    state: link
  become: yes

- name: Install tools
  ansible.builtin.apt:
    pkg:
      - dnsutils
      - iotop
      - screen
      - procinfo
      - traceroute
    update_cache: yes
  become: yes

- name: Disable sleep on lid close
  ansible.builtin.lineinfile:
    path: /etc/systemd/logind.conf
    line: '{{ item }}'
  with_items:
    - HandleLidSwitch=ignore
    - HandleLidSwitchDocked=ignore
    - LidSwitchIgnoreInhibited=no
  notify: Restart systemd-logind service
  become: yes

- name: Place rc.local
  ansible.builtin.copy:
    src: rc.local
    dest: /etc/rc.local
    owner: root
    group: root
    mode: 0777
  become: yes

- import_tasks: live-patch.yml
  become: yes

- import_tasks: unattended-upgrades.yml
  become: yes

- import_tasks: telegraf.yml
  become: yes
