- name: Install unattended-upgrades
  apt:
    name: unattended-upgrades
    state: '{{ UNATTENDED_UPGRADES_STATE }}'
    update_cache: yes
  become: yes

- name: Place unattended-upgrades conf
  template:
    src: 50unattended-upgrades
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
  notify: Restart unattended-upgrades service
  when: UNATTENDED_UPGRADES_STATE == 'present'

- name: Place apt conf
  copy:
    src: 20auto-upgrades
    dest: /etc/apt/apt.conf.d/20auto-upgrades
  when: UNATTENDED_UPGRADES_STATE == 'present'

- name: Remove unattended-upgrades conf
  file:
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    state: absent
  when: UNATTENDED_UPGRADES_STATE == 'absent'

- name: Remove apt conf
  file:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    state: absent
  when: UNATTENDED_UPGRADES_STATE == 'absent'

- name: Start unattended-upgrades service
  service:
    name: unattended-upgrades
    state: started
    enabled: yes
  when: UNATTENDED_UPGRADES_STATE == 'present'
