---

- name: Install MicroK8s
  snap:
    name: microk8s
    classic: yes
    channel: "{{ MICROK8S_CHANNEL }}"

- name: Add registry to docker
  copy:
    src: docker_daemon.json
    dest: /etc/docker/daemon.json
  notify: restart docker service

- name: Adding user {{ USER }} to microk8s group
  user:
    name: "{{ USER }}"
    groups: microk8s
    append: yes

- name: Add alt_name to microk8s template
  lineinfile:
    path: /var/snap/microk8s/current/certs/csr.conf.template
    insertbefore: '^IP.1 ='
    line: DNS.6 = {{ inventory_hostname }}

- name: Get enabled MicroK8s addons
  shell: microk8s status | grep enabled | awk -F ':' '{print $1}'
  register: microk8s_enabled_addons

- name: Enable MicroK8s addons
  command: microk8s enable {{ item }}
  loop: "{{ MICROK8S_ADDONS }}"
  when: item not in microk8s_enabled_addons.stdout_lines

# TODO: --resolv-conf to be deprecated but currently doesn't work
# https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/
# https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file
# - name: Copy kubelet config
#   copy:
#     src: kubelet.conf
#     dest: /etc/kubelet.conf

- name: Update MicroK8s resolve-conf
  lineinfile:
    path: /var/snap/microk8s/current/args/kubelet
    # line: --config=/etc/kubelet.conf
    line: --resolv-conf=/run/systemd/resolve/resolv.conf
  notify: Restart kubelet service
