---

- name: Check if Bat version is installed
  command: bat --version
  register: bat_version_command
  ignore_errors: yes
  changed_when: False

- name: set Bat version fact
  set_fact:
    bat_version: "{{ bat_version_command.stdout | regex_search(regexp) }}"
  vars:
    regexp: '[0-9]+\.[0-9]+\.[0-9]+'
    cacheable: yes

- name: Download Bat
  unarchive:
    src: https://github.com/sharkdp/bat/releases/download/v{{ BAT_VERSION }}/bat-v{{ BAT_VERSION }}-x86_64-unknown-linux-gnu.tar.gz
    dest: /tmp
    remote_src: yes
  when: bat_version_command.rc != 0 or BAT_VERSION != bat_version

- name: Install Bat
  command: mv -f /tmp/bat-v{{ BAT_VERSION }}-x86_64-unknown-linux-gnu/bat /usr/local/bin/bat
  when: bat_version_command.rc != 0 or BAT_VERSION != bat_version

- name: Set execute permissions for bat
  file:
    path: /usr/local/bin/k9s
    mode: u+x
    modification_time: preserve
    access_time: preserve
