- name: install dependencies
  apt:
    pkg:
      - gcc
      - python3-dev
      - python3-venv
    update_cache: yes

- name: Install bpytop pip
  pip:
    name:
      - bpytop==1.0.54
    virtualenv: /opt/bpytop/venv
    virtualenv_command: /usr/bin/python3 -m venv

- name: link bpytop
  file:
    src: /opt/bpytop/venv/bin/bpytop
    dest: /usr/local/bin/bpytop
    state: link
