- name: Check if Exa version is installed
  ansible.builtin.command: exa --version
  register: exa_version_command
  ignore_errors: yes
  changed_when: False

- name: set Exa version fact
  set_fact:
    exa_version: "{{ exa_version_command.stdout | regex_search(regexp) }}"
  vars:
    regexp: '[0-9]+\.[0-9]+\.[0-9]+'
    cacheable: yes
  when: exa_version_command.rc == 0

- name: Download Exa x86_64
  ansible.builtin.unarchive:
    src: https://github.com/ogham/exa/releases/download/v{{ EXA_VERSION }}/exa-linux-x86_64-v{{ EXA_VERSION }}.zip
    dest: /tmp
    remote_src: yes
  when: exa_version_command.rc != 0 or EXA_VERSION != exa_version

- name: Install Exa
  ansible.builtin.command: mv -f /tmp/bin/exa /usr/local/bin/exa
  when:
    - exa_version_command.rc != 0 or EXA_VERSION != exa_version

- name: Set execute permissions for exa x86_64
  ansible.builtin.file:
    path: /usr/local/bin/exa
    mode: a+x
