- name: Install haste
  community.general.gem:
    name: haste
    version: 0.2.3
    bindir: /usr/local/bin
    state: present

- name: make haste executable
  ansible.builtin.file:
    path: /usr/local/bin/haste
    owner: root
    group: root
    mode: '0755'
