# install hstr

- name: Add hstr Repository
  apt_repository:
    repo: ppa:ultradvorka/ppa
  become: yes

- name: Install hstr
  ansible.builtin.apt:
    name: hstr
    update_cache: yes
  become: yes
