---
# Install and setup k9s

- name: Check if K9s version is installed
  command: k9s version
  register: k9s_version
  ignore_errors: yes

- name: Install K9s
  unarchive:
    src: "https://github.com/derailed/k9s/releases/download/v{{ K9S_VERSION }}/k9s_Linux_x86_64.tar.gz"
    dest: /usr/local/bin
    remote_src: yes
  when: k9s_version.rc != 0 or K9S_VERSION not in k9s_version.stdout

- name: Set execute permissions for k9s
  file:
    path: /usr/local/bin/k9s
    mode: u+x
    modification_time: preserve
    access_time: preserve
  when: k9s_version.rc != 0 or K9S_VERSION not in k9s_version.stdout
