---

- name: Install my bash_profile
  copy:
    src: bash_profile
    dest: /home/dennis/.bash_profile

- name: Install tools
  apt:
    pkg:
      - curl
      - make
      - screen
    update_cache: yes
  become: yes

- name: Update DNS nameservers
  lineinfile:
    path: /etc/netplan/00-installer-config.yaml
    regex: '^        addresses: \['
    line: "        addresses: [{{ PIHOLE_SERVER_IP }}, 8.8.8.8, 8.8.4.4]"
  become: yes
  notify: Apply Netplan

- import_tasks: ntp.yml
  become: yes

- import_tasks: docker.yml
  become: yes

- import_tasks: microk8s.yml
  become: yes
