- name: Install tools
  apt:
    pkg:
      - curl
      - screen
      - unzip
    update_cache: yes
  become: yes

- import_tasks: bat.yml
  become: yes

- import_tasks: hstr.yml
  when: ansible_architecture == 'x86_64'

- import_tasks: bpytop.yml
  become: yes
