- import_tasks: nginx.yml
  become: yes

- import_tasks: nfs.yml
  become: yes

- import_tasks: pihole.yml
  become: yes

- import_tasks: node_stats_lcd.yml
  become: yes

- import_tasks: nginx_stats_lcd.yml
  become: yes

- import_tasks: pihole_stats_lcd.yml
  become: yes

- import_tasks: docker.yml
  become: yes

- import_tasks: dc-services.yml
  become: yes
