- name: Restart sshd service
  service:
    name: sshd
    state: restarted
  become: true

- import_tasks: nginx.yml
  become: true

- import_tasks: pihole.yml
  become: true

- import_tasks: node_stats_lcd.yml
  become: true

- import_tasks: nginx_stats_lcd.yml
  become: true

- import_tasks: pihole_stats_lcd.yml
  become: true

- import_tasks: telegraf.yml
  become: true
