- import_tasks: nginx.yml
  become: yes

- import_tasks: fail2ban.yml
  become: yes

- import_tasks: nfs.yml
  become: yes

- import_tasks: nginx_stats_lcd.yml
  become: yes

- import_tasks: pihole_stats_lcd.yml
  become: yes
