- import_tasks: nginx.yml
  become: true

- import_tasks: pihole.yml
  become: true

- import_tasks: node_stats_lcd.yml
  become: true

- import_tasks: nginx_stats_lcd.yml
  become: true

- import_tasks: pihole_stats_lcd.yml
  become: true

- import_tasks: k8s_stats_lcd.yml
  become: true
